language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; import TrackingLoopFilters; cd(joinpath(dirname(pathof(Tracking)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
