language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

coveralls: true

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
